name: Exec Rspec
run-name: Matrix building for ruby 3.0 âœ–ï¸ ã€rails 6.0ã€‘ ğŸš€
on: [push]

jobs:
  ruby_2_7:
    strategy:
      fail-fast: false
      matrix:
        arversion: ['6_0_6']
    runs-on: ubuntu-22.04
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails${{ matrix.arversion }}.gemfile
      MYSQL_PWD: root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler: latest
          bundler-cache: true
      - name: Start mysql
        run: sudo systemctl start mysql.service
      - name: Reset DB
        run: bundle exec rake turntable:db:reset
      - name: Run RSpec
        run: RUBYOPT='-W:deprecated' bundle exec rake spec
