name: Exec Rspec
run-name: Matrix building for ruby 3.2 âœ–ï¸ ã€rails 6.1ã€‘ ğŸš€
on: [push]

jobs:
  ruby_3_2:
    strategy:
      fail-fast: false
      matrix:
        arversion: ['6_1_0', '6_1_1', '6_1_2', '6_1_3', '6_1_4', '6_1_5', '6_1_6', '6_1_7']
    runs-on: ubuntu-22.04
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails${{ matrix.arversion }}.gemfile
      MYSQL_PWD: root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler: latest
          bundler-cache: true
      - name: Start mysql
        run: sudo systemctl start mysql.service
      - name: Reset DB
        run: bundle exec rake turntable:db:reset
      - name: Run RSpec
        run: RUBYOPT='-W:deprecated' bundle exec rake spec
